export const ADMIN_ROUTER = '/admin'
export const LOGIN_ROUTER = '/login'
export const REGISTRATION_ROUTER = '/registration'
export const SHOP_ROUTER = '/'
export const BASKET_ROUTER = '/basket'
export const ITEM_ROUTER = '/item'